### ISSUE TITLE
ordered pull consumer is not working

### ISSUE THREAD

**Issue by asnimansari** [nats-io/nats.rs#1145] opened 2023-10-30 05:19 UTC
### Observed behaviour

When I try to create an ordered pull consumer as per the documentation https://docs.rs/async-nats/latest/async_nats/jetstream/consumer/type.OrderedPullConsumer.html

Code I used 
```
         .create_consumer(
                
                jetstream::consumer::pull::OrderedConfig {
                    name: Some("consumer".to_string()),
                    ..Default::default()
                },
            )
```

I received the following error
```
Failed to create consumer: Error { kind: JetStream(Error { code: 400, err_code: ErrorCode(10084), description: Some("consumer in pull mode requires ack policy") }), source: None }
``` 

### Expected behavior

Should build and work

### Server and client version

Nats server  2.10.3

**Comment by Jarema** [comment] 2023-10-30 06:32
Thanks for filling the issue!

This is a server error reported on older version (If I recall correctlu <2.9).

I see you reported using nats server 2.10.3, but it seems that the server that is meta group leader is not that version.

Can you elaborate a little on your topology?
(basic cluster info, leaf nodes, etc)

**Comment by asnimansari** [comment] 2023-10-31 11:18
It is a basic 3 node cluster.

**Comment by Jarema** [comment] 2023-10-31 12:36
This error is returned from the server, and 2.10.3 does not have this condition in the code path at all.
This error is not there since at least version 2.2 of the server.

Does your cluster have homogenous versions across the nodes? Meaning all of them are running on 2.10?
If the server to which you are connected would be lower than 2.9, you would get some different client side error, but the meta leader for JetStream seems to be a different version.

Please paste here nats-servers log from when it starts.

**Comment by asnimansari** [comment] 2023-10-31 14:35
Yes, the retention policy is `WorkQueuePolicy`

**Comment by Jarema** [comment] 2023-10-31 15:51
You can't use ordered pull consumer with work queue stream, as it uses AckNone.

**Comment by Jarema** [comment] 2023-11-02 08:25
I'm closing this issue, as this is not a bug.
I also issued a PR against the server to improve the error message.

**Closed by Jarema** 2023-11-02 08:25 UTC
Labels: defect
